[fix][typescript] house-robber-iii
labuladong/fucking-algorithm pull request #1406
Opened 2023-05-30 10:25 UTC by yyj08070631

Fixes https://github.com/labuladong/fucking-algorithm/issues/1396

我修改的是如下题目的 typescript/javascript 解法：

https://leetcode.cn/problems/house-robber-iii/

通过截图如下：
<img width="1628" alt="image" src="https://github.com/labuladong/fucking-algorithm/assets/27988527/96927422-faab-4faf-a180-454f5fc780df">

2023-06-02 08:37 UTC, labuladong requested changes
感谢你的 PR，多语言代码的目的是帮助不同背景的朋友辅助理解解法思路，所以每个语言的解法的思路和注释都应该尽量相同。请基于原有代码的思路进行修改，并保留所有注释，谢谢！

2023-06-09 08:56 UTC, yyj08070631 commented
更新通过截图如下：
<img width="870" alt="image" src="https://github.com/labuladong/fucking-algorithm/assets/27988527/40606def-c06a-4a98-95d8-78db19b07266">

2023-06-13 10:06 UTC, labuladong commented
确实，这样可以通过测试用例，但这样并不是最好的。因为力扣的全局变量不会清除，即每个 test case 其实用的都是同一个 memo 变量。建议在 `rob` 函数内容套一个名为 `dp` 的高阶函数来递归，这样技能避免重复创建 `memo`，也能避免全局变量。

2023-06-14 09:31 UTC, yyj08070631 commented
> 确实，这样可以通过测试用例，但这样并不是最好的。因为力扣的全局变量不会清除，即每个 test case 其实用的都是同一个 memo 变量。建议在 `rob` 函数内套一个名为 `dp` 的高阶函数来递归，这样技能避免重复创建 `memo`，也能避免全局变量。

原来如此，我按照这个方式改了，重新提下review~
<img width="853" alt="image" src="https://github.com/labuladong/fucking-algorithm/assets/27988527/0139def5-8655-444d-bc47-1547b38c899c">

2023-06-14 09:37 UTC, labuladong commented on 多语言解法代码/solution_code.md
> +    dp(root)
结果似乎没有 return

2023-06-14 09:39 UTC, yyj08070631 commented on 多语言解法代码/solution_code.md
> +    dp(root)
😂跑完忘记把代码更新回仓库，重新提交了

2023-06-14 09:46 UTC, labuladong approved these changes
感谢你的修正！

2023-06-14 09:46 UTC, merged